=== Agoelia/add-mod-near-future-tech/generated/mod_manifest.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "schema_version": {
      "const": "1.0"
    },
    "package_type": {
      "enum": [
        "mod",
        "soundpack"
      ]
    },
    "id": {
      "type": "string",
      "minLength": 1,
      "pattern": "^(?=.*\\S)[^/\\\\?#]+$"
    },
    "display_name": {
      "type": "string"
    },
    "short_description": {
      "type": "string",
      "maxLength": 200
    },
    "description": {
      "type": "string"
    },
    "author": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "type": "string"
    },
    "homepage": {
      "type": "string",
      "format": "uri"
    },
    "version": {
      "type": "string"
    },
    "previous_releases": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "version": {
            "type": "string"
          },
          "source": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "github_archive",
                  "gitlab_archive",
                  "direct_url"
                ]
              },
              "url": {
                "type": "string",
                "format": "uri"
              },
              "commit_sha": {
                "type": "string",
                "pattern": "^[a-f0-9]{40}$"
              },
              "extract_path": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "url"
            ]
          },
          "released_at": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "version",
          "source"
        ]
      }
    },
    "yanked": {
      "type": "object",
      "properties": {
        "reason": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "reason"
      ]
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "conflicts": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "source": {
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "github_archive",
            "gitlab_archive",
            "direct_url"
          ]
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "commit_sha": {
          "type": "string",
          "pattern": "^[a-f0-9]{40}$"
        },
        "extract_path": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "url"
      ]
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "icon_url": {
      "type": "string"
    },
    "modinfo_url": {
      "type": "string",
      "format": "uri"
    },
    "uses_lua": {
      "type": "boolean"
    },
    "lua_api_version": {
      "type": "integer"
    },
    "autoupdate": {
      "type": "object",
      "properties": {
        "type": {
          "enum": [
            "tag",
            "commit"
          ]
        },
        "update_url": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        },
        "regex": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    },
    "parent": {
      "type": "string",
      "minLength": 1,
      "pattern": "^(?=.*\\S)[^/\\\\?#]+$"
    },
    "last_updated": {
      "type": "string",
      "format": "date-time"
    }
  },
  "required": [
    "schema_version",
    "id",
    "display_name",
    "short_description",
    "author",
    "license",
    "version",
    "source"
  ]
}

=== Agoelia/add-mod-near-future-tech/generated/mods/mutant_animals.json
{
  "schema_version": "1.0",
  "id": "mutant_animals",
  "display_name": "Mutant Animals",
  "short_description": "Expansion for animals that makes them evolve over time into new mutated versions. Some of them, though, they are weird, become tameable, very friendly, useful mutated versions. Some of them, however,",
  "author": [
    "Sunshine"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Mutant_Animals",
  "version": "0.0.0",
  "yanked": {
    "reason": "Kenan modpack entries are no longer tracked in this registry."
  },
  "dependencies": {
    "bn": ">=0.9.1"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip",
    "commit_sha": "142b53ba0079e9c0aea3e8e674ad17a7dc193d07",
    "extract_path": "Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Mutant_Animals"
  },
  "categories": [
    "creatures"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/142b53ba0079e9c0aea3e8e674ad17a7dc193d07/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Mutant_Animals/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "master"
  },
  "last_updated": "2026-06-08T09:00:53+09:00"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/xl_armors_makeshift_stuff.json
{
  "schema_version": "1.0",
  "id": "xl_armors_makeshift_stuff",
  "display_name": "XL Armors for More Makeshift Stuff",
  "short_description": "This is an extension that adds XL armors for the More Makeshift Stuff mod.",
  "description": "This is an extension that adds XL armors for the More Makeshift Stuff mod.",
  "author": [
    "leoCottret"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/leoCottret/cbn-leocottret-mods/tree/main/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_More_Makeshift_Stuff",
  "version": "2026.6.10-2e94b3e",
  "previous_releases": [
    {
      "version": "0.0.0",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "57778ad68c1271f1e7069e5c6a0cebdfd40fa01a",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_More_Makeshift_Stuff"
      },
      "released_at": "2026-05-16T09:24:44.653Z"
    },
    {
      "version": "2026.6.8-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_More_Makeshift_Stuff"
      },
      "released_at": "2026-06-08T03:02:33.954Z"
    },
    {
      "version": "2026.6.9-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_More_Makeshift_Stuff"
      },
      "released_at": "2026-06-09T02:39:22.942Z"
    }
  ],
  "yanked": {
    "reason": "can re-fit armors into XL"
  },
  "dependencies": {
    "makeshift_stuff": "*"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
    "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
    "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_More_Makeshift_Stuff"
  },
  "categories": [
    "content"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/leoCottret/cbn-leocottret-mods/57778ad68c1271f1e7069e5c6a0cebdfd40fa01a/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_More_Makeshift_Stuff/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "main"
  },
  "last_updated": "2026-06-10T02:55:56.025Z"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/xl_armors_secronom_lore_expansion.json
{
  "schema_version": "1.0",
  "id": "xl_armors_secronom_lore_expansion",
  "display_name": "XL Armors for Secronom expansion",
  "short_description": "This is the main XL armors mod, that adds XL armors for secronom.",
  "description": "This is the main XL armors mod, that adds XL armors for secronom.",
  "author": [
    "leoCottret",
    "LucioFurnari"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/leoCottret/cbn-leocottret-mods/tree/main/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_secronom_lore_expansion",
  "version": "2026.6.10-2e94b3e",
  "previous_releases": [
    {
      "version": "0.0.0",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "57778ad68c1271f1e7069e5c6a0cebdfd40fa01a",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_secronom_lore_expansion"
      },
      "released_at": "2026-05-16T09:24:44.658Z"
    },
    {
      "version": "2026.6.8-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_secronom_lore_expansion"
      },
      "released_at": "2026-06-08T03:03:07.033Z"
    },
    {
      "version": "2026.6.9-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_secronom_lore_expansion"
      },
      "released_at": "2026-06-09T02:39:58.838Z"
    }
  ],
  "yanked": {
    "reason": "can re-fit armors into XL"
  },
  "dependencies": {
    "bn": ">=0.9.1",
    "secronom": "*",
    "secronom_lore_expansion": "*"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
    "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
    "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_secronom_lore_expansion"
  },
  "categories": [
    "content"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/leoCottret/cbn-leocottret-mods/57778ad68c1271f1e7069e5c6a0cebdfd40fa01a/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_secronom_lore_expansion/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "main"
  },
  "last_updated": "2026-06-10T02:55:45.991Z"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/xl_armors_cbm_arms.json
{
  "schema_version": "1.0",
  "id": "xl_armors_cbm_arms",
  "display_name": "XL Armors for CBM Equipment",
  "short_description": "This is an extension that adds XL armors for the CBM Equipment mod.",
  "description": "This is an extension that adds XL armors for the CBM Equipment mod.",
  "author": [
    "leoCottret"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/leoCottret/cbn-leocottret-mods/tree/main/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms",
  "version": "2026.6.25-2a87768",
  "previous_releases": [
    {
      "version": "0.0.0",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "57778ad68c1271f1e7069e5c6a0cebdfd40fa01a",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-05-16T09:24:44.651Z"
    },
    {
      "version": "2026.6.8-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-08T03:02:28.153Z"
    },
    {
      "version": "2026.6.9-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-09T02:39:16.682Z"
    },
    {
      "version": "2026.6.10-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-10T02:55:42.675Z"
    },
    {
      "version": "2026.6.11-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-11T02:58:15.040Z"
    },
    {
      "version": "2026.6.12-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-12T03:01:29.477Z"
    },
    {
      "version": "2026.6.13-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-13T02:48:49.081Z"
    },
    {
      "version": "2026.6.14-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-14T02:59:04.971Z"
    },
    {
      "version": "2026.6.15-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-15T03:32:37.879Z"
    },
    {
      "version": "2026.6.16-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-16T03:34:32.837Z"
    },
    {
      "version": "2026.6.17-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-17T03:26:35.913Z"
    },
    {
      "version": "2026.6.18-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-18T03:01:23.506Z"
    },
    {
      "version": "2026.6.19-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-19T03:55:50.939Z"
    },
    {
      "version": "2026.6.20-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
      },
      "released_at": "2026-06-20T02:48:52.097Z"
    }
  ],
  "yanked": {
    "reason": "can re-fit armors into XL"
  },
  "dependencies": {
    "cbm_arms": "*"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
    "commit_sha": "2a877689a9c119da012e84146b1355f325c3a0bd",
    "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms"
  },
  "categories": [
    "content"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/leoCottret/cbn-leocottret-mods/57778ad68c1271f1e7069e5c6a0cebdfd40fa01a/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_CBMArms/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "main"
  },
  "last_updated": "2026-06-25T02:41:17.787Z"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/xl_armors_tcw_box.json
{
  "schema_version": "1.0",
  "id": "xl_armors_tcw_box",
  "display_name": "XL Armors for [Demo] Doomsday Reserve Box",
  "short_description": "This is an extension that adds XL armors for the [Demo] Doomsday Reserve Box mod.",
  "description": "This is an extension that adds XL armors for the [Demo] Doomsday Reserve Box mod.",
  "author": [
    "leoCottret"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/leoCottret/cbn-leocottret-mods/tree/main/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box",
  "version": "2026.6.15-53b55a3",
  "previous_releases": [
    {
      "version": "0.0.0",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "57778ad68c1271f1e7069e5c6a0cebdfd40fa01a",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-05-16T09:24:44.656Z"
    },
    {
      "version": "2026.6.8-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-08T03:02:50.633Z"
    },
    {
      "version": "2026.6.9-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-09T02:39:41.536Z"
    },
    {
      "version": "2026.6.10-2e94b3e",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "2e94b3ec069793086efe73923b091a36815c27ae",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-10T02:55:42.791Z"
    },
    {
      "version": "2026.6.11-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-11T02:58:15.910Z"
    },
    {
      "version": "2026.6.12-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-12T03:01:29.744Z"
    },
    {
      "version": "2026.6.13-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-13T02:48:49.341Z"
    },
    {
      "version": "2026.6.14-53b55a3",
      "source": {
        "type": "github_archive",
        "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
        "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
        "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
      },
      "released_at": "2026-06-14T02:59:05.756Z"
    }
  ],
  "yanked": {
    "reason": "can re-fit armors into XL"
  },
  "dependencies": {
    "tcw_box": "*"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/leoCottret/cbn-leocottret-mods/archive/refs/heads/main.zip",
    "commit_sha": "53b55a3b6e7fc2632f50111f560f4a72bdb7d13b",
    "extract_path": "MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box"
  },
  "categories": [
    "content"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/leoCottret/cbn-leocottret-mods/57778ad68c1271f1e7069e5c6a0cebdfd40fa01a/MODS/XL_ARMORS_KENAN_MODPACK/XL_Armors_TCW_Box/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "main"
  },
  "last_updated": "2026-06-15T03:32:37.929Z"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/gun_bow.json
{
  "schema_version": "1.0",
  "id": "gun_bow",
  "display_name": "Gunbow",
  "short_description": "adds one rare bow with custom-made sound fx",
  "description": "adds one rare bow with custom-made sound fx",
  "author": [
    "hamatk"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/hamatk/CataclysmBN_Mod_MachineBow/tree/main/gun_bow",
  "version": "0.0.0",
  "dependencies": {
    "bn": ">=0.9.1"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/hamatk/CataclysmBN_Mod_MachineBow/archive/refs/heads/main.zip",
    "commit_sha": "a7ad0a631fb7dfdd07f6de249971c3699d584509",
    "extract_path": "gun_bow"
  },
  "categories": [
    "content"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/hamatk/CataclysmBN_Mod_MachineBow/a7ad0a631fb7dfdd07f6de249971c3699d584509/gun_bow/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "main"
  },
  "last_updated": "2026-05-16T09:25:29.560Z"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/necro_find.json
{
  "schema_version": "1.0",
  "id": "necro_find",
  "display_name": "Necropolis Actually Findable",
  "short_description": "Tired of all that futile search for Necropolis? Sick after checking 5165846512354 overmaps to no avail? Worry no more, this mod solves that problem! It makes Necropolis findable by making it spawn in",
  "author": [
    "Stormtrooper"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/tree/master/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Necropolis_findable",
  "version": "0.0.0",
  "yanked": {
    "reason": "Kenan modpack entries are no longer tracked in this registry."
  },
  "dependencies": {
    "bn": ">=0.9.1"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/archive/refs/heads/master.zip",
    "commit_sha": "142b53ba0079e9c0aea3e8e674ad17a7dc193d07",
    "extract_path": "Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Necropolis_findable"
  },
  "categories": [
    "rebalance"
  ],
  "modinfo_url": "https://raw.githubusercontent.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack/142b53ba0079e9c0aea3e8e674ad17a7dc193d07/Kenan-BrightNights-Structured-Modpack/High-Maintenance-Huge-Mods/Necropolis_findable/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "commit",
    "branch": "master"
  },
  "last_updated": "2026-06-22T03:33:52Z"
}

=== Agoelia/add-mod-near-future-tech/generated/mods/overhaul.json
{
  "schema_version": "1.0",
  "id": "overhaul",
  "display_name": "Overhaul Tileset",
  "short_description": "Anime-style graphical tileset for Bright Nights.",
  "description": "Anime-style tileset mod with character, appearance, mutation, and interface graphics for Bright Nights.",
  "author": [
    "비창",
    "고양이",
    "Xotto",
    "로갤"
  ],
  "license": "ALL-RIGHTS-RESERVED",
  "homepage": "https://github.com/scarf005/Overhaul",
  "version": "0.0.2",
  "dependencies": {
    "bn": ">=0.9.1"
  },
  "source": {
    "type": "github_archive",
    "url": "https://github.com/scarf005/Overhaul/archive/refs/tags/v0.0.2.zip",
    "commit_sha": "d06d0f24ac4be9435ec72a96edc301953140b0ee",
    "extract_path": "Overhaul-0.0.2/overhaul"
  },
  "categories": [
    "graphical"
  ],
  "tags": [
    "tileset",
    "appearance"
  ],
  "icon_url": "https://raw.githubusercontent.com/scarf005/Overhaul/v0.0.2/icon.webp",
  "modinfo_url": "https://raw.githubusercontent.com/scarf005/Overhaul/d06d0f24ac4be9435ec72a96edc301953140b0ee/overhaul/modinfo.json",
  "uses_lua": false,
  "autoupdate": {
    "type": "tag",
    "update_url": "https://github.com/scarf005/Overhaul",
    "regex": "^v[0-9]"
  },
  "last_updated": "2026-06-21T02:17:05Z"
}
